FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Isha MDM API

API for Isha Master Data Management (MDM) System

# Get contacts [GET /contacts]
# Get contacts by ids [GET /contacts{?ids}]
# Get contact by id [GET /contacts/{id}]
# Add contact [POST /contacts]
# Update contact [PUT /contacts/{id}]

# Match Contacts [GET /contacts/match{?q}]
# Merge Contacts [POST /contacts/merge]
# Suggest merged contact [GET /contacts/merge/suggest{?ids}]
# Antimatch contacts [POST /contacts/merge/antimatch]

# Get contact match groups [GET /contacts/match-groups]
# Get matched contacts [GET /contacts/match-groups/{id}]
# Add contact match group [POST /contacts/match-groups]
# Remove contact match group [DELETE /match-groups/contact/{id}]

# Get constants [GET /constants{?entityType}{&attribute,parentValue}]
# Get countries [GET /countries]
# Get systems [GET /systems]
# Get system [GET /systems/{id}]

# Get object lables [GET /object-labels]

getConstants [GET]:                   mdm-server/api/constants?entityType=address&attribute=stateProvince&parentValue=india
getCountryConstants:                   mdm-server/api/countries [GET]

getSystemInfo:                             mdm-server/api/systems [GET]
getSystemInfo:                             mdm-server/api/systems/12 [GET]

getObjectLabels:                           mdm-server/api/object-labels?name=contactInfo [GET]









## Contacts [/contacts]

### List most recently added contacts [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]



### Create a New Contact [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /contact/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Contact [/contacts/{id}]

### List most recently added contacts [GET]

+ Response 200 (application/json)
